mambojs/mambo-ui

src/index.html, src/ui/components/Button/Button-Orange.css, src/ui/components/Button/Button.js, src/ui/components/Button/story/button.js, src/ui/components/ButtonGroup/ButtonGroup-Orange.css, src/ui/components/ButtonGroup/story/buttonGroup.js, src/ui/themes/m-default-orange.css, src/ui/tools/Theme.js
add primary and secondary orange buttons
=> create m-default-orange.css. add colors

documentation/documentation.md, server.cjs, setup/esbuild.config.cjs, setup/gulpfile.js, src/components/storyboard/storyboard.css, src/components/storyboard/storyboard.js, src/css/mambo-ui-0.0.1-orange.css, src/css/mambo-ui-0.0.1.css, src/index.html, src/js/index.js, src/ui/components/Button/story/button.js, src/ui/components/Combobox/Combobox.js, src/ui/tools/Theme.js
fix combobox button selected error
=> add theme selection. add home documentation. add scrollbar css design

src/components/storyboard/storyboard.js, src/js/index.js, src/ui/tools/Theme.js
- Refactor Theme stylesheet swap
=> Refactor Theme stylesheets

src/components/storyboard/story.css, src/ui/components/Checkbox/Checkbox-Orange.css, src/ui/components/Radio/Radio-Orange.css, src/ui/components/Radio/Radio.css, src/ui/components/Radio/Radio.js, src/ui/components/Radio/story/radio.js, src/ui/components/RadioGroup/RadioGroup.js, src/ui/components/RadioGroup/story/radioGroup.js
add more orange classes
add position to radio. add orange styles too
=> create more orange css classes. add previousLinkClass to theme

src/components/storyboard/storyboard.css, src/ui/components/Button/Button-Orange.css, src/ui/components/ButtonGroup/ButtonGroup-Orange.css, src/ui/components/Checkbox/Checkbox-Orange.css, src/ui/components/Combobox/Combobox-Orange.css, src/ui/components/Combobox/Combobox.css, src/ui/components/Combobox/Combobox.js, src/ui/components/Combobox/story/combobox.js, src/ui/components/Input/Input-Orange.css, src/ui/components/Radio/Radio-Orange.css, src/ui/themes/m-default.css, src/ui/themes/m-orange.css
add styles to combobox
change button size from px to rem
=> fix combobox width and height

.gitignore, .idea/workspace.xml, src/ui/components/Button/Button.js, src/ui/components/Button/story/button.js, src/ui/components/Input/Input-Orange.css, src/ui/components/Input/Input.js, src/ui/components/Input/story/input.js, src/ui/components/Textarea/Textarea-Orange.css, src/ui/tools/Theme.js
=> add password input with toggle button

.idea/workspace.xml, src/components/storyboard/storyboard.css, src/components/storyboard/storyboard.js, src/ui/components/Combobox/Combobox-Orange.css, src/ui/components/Combobox/Combobox.css, src/ui/components/Input/Input-Orange.css, src/ui/components/Input/Input.css, src/ui/components/Input/Input.js, src/ui/components/Input/story/input.js, src/ui/components/Textarea/Textarea-Orange.css, src/ui/components/Textarea/Textarea.css, src/ui/components/Textarea/Textarea.js, src/ui/components/Textarea/story/textarea.js, src/ui/themes/m-default.css, src/ui/themes/m-orange.css, src/ui/tools/Tags.js, src/ui/tools/Theme.js
add new orange and default styles to textarea. Add editable state
replace rem values with vars
=> create span. Add edit button. Rename clear button

.idea/workspace.xml, src/ui/components/Grid/Grid.js, src/ui/components/MapBox/MapBox.js
Change two dom.append methods to element.appendChild methods.
=> replace dom.append

.idea/workspace.xml, src/components/storyboard/storyboard.css, src/ui/components/Switch/Switch-Orange.css, src/ui/components/Switch/Switch.css, src/ui/components/Switch/Switch.js, src/ui/components/Switch/story/switch.js, src/ui/themes/m-orange.css, src/ui/tools/Tags.js, src/ui/tools/Theme.js
add text and orange theme to switch
add font size xxs to orange theme
=> add text. add orange theme

.idea/workspace.xml, src/components/storyboard/storyboard.css, src/ui/components/FileChooser/FileChooser-Orange.css, src/ui/components/FileChooser/FileChooser.css, src/ui/components/FileChooser/FileChooser.js, src/ui/components/FileChooser/story/fileChooser.js, src/ui/components/Grid/Grid-Orange.css, src/ui/components/Grid/Grid.css, src/ui/components/Grid/Grid.js, src/ui/components/Grid/story/grid.js, src/ui/tools/Theme.js
Fix dialog: button wasn't opennig window dialog
Fix filechooser: button was not visible
Add orange theme to grid buttons
Add orange theme to grid input
Add vars to grid css
=> Add orange theme to grid. review props extention on childs

.idea/workspace.xml, setup/config.cjs, src/ui/components/Button/Button-Orange.css, src/ui/components/Button/Button.css, src/ui/components/Button/Button.js, src/ui/components/ButtonGroup/ButtonGroup-Orange.css, src/ui/components/ButtonGroup/ButtonGroup.css, src/ui/components/ButtonGroup/ButtonGroup.js, src/ui/components/ButtonGroup/story/buttonGroup.js, src/ui/components/Grid/Grid-Orange.css, src/ui/components/Input/Input-Orange.css, src/ui/components/Input/Input.css, src/ui/components/Input/story/input.js, src/ui/components/Tab/story/tab.js, src/ui/themes/m-orange.css
add css vars
add webstorm config
=> feat (buttons): support for column layout with text and icons

.editorconfig, documentation/archived/documentation-0.0.2.md, documentation/documentation.md, public/css/mambo-ui-0.0.2-orange.css, public/css/mambo-ui-0.0.2-purple.css, public/css/mambo-ui-0.0.2.css, public/js/mambo-ui-0.0.2-stories.js, public/js/mambo-ui-0.0.2.js, src/ui/components/Button/Button-Orange.css, src/ui/components/Button/Button-Purple.css, src/ui/components/Button/Button.css, src/ui/components/ButtonGroup/ButtonGroup-Orange.css, src/ui/components/ButtonGroup/ButtonGroup-Purple.css, src/ui/components/DatePicker/DatePicker-Orange.css, src/ui/components/DatePicker/DatePicker-Purple.css, src/ui/components/DatePicker/DatePicker.css, src/ui/components/Listbox/Listbox-Orange.css, src/ui/components/Listbox/Listbox-Purple.css, src/ui/components/Listbox/Listbox.css, src/ui/components/Search/Search-Orange.css, src/ui/components/Search/Search-Purple.css, src/ui/components/Search/Search.css, src/ui/components/Slider/Slider.js, src/ui/components/Tab/story/tab.js, src/ui/tools/Theme.js
Update documentation with updated event names and new components
Add new build files to the public directory (JS and CSS)
Updated button styling to fill entire width of its parent container
=> Update documentation. Fix orange and purple styles.

.idea/workspace.xml, src/ui/components/Input/Input-Orange.css, src/ui/components/Input/Input-Purple.css, src/ui/components/Input/Input.css, src/ui/components/Input/Input.js, src/ui/components/Input/story/input.js, src/ui/themes/m-purple.css
Add purple styles to input. 
Fix inpot label position. add default, purple and orange styles to label
=> add more purple styles to input

.idea/workspace.xml, public/css/story.css, src/ui/components/Combobox/Combobox-Orange.css, src/ui/components/Combobox/Combobox-Purple.css, src/ui/components/Combobox/Combobox.css, src/ui/components/Combobox/Combobox.js, src/ui/components/Combobox/story/combobox.js, src/ui/components/Input/Input.js, src/ui/tools/Tags.js, src/ui/tools/Theme.js
Added label support for the combobox component.
Wrapped labels, input, and buttons within a container for better structure and styling.
Use CSS vars in combobox themes
=> Add label to Combobox

.idea/workspace.xml, public/css/mambo-ui-0.0.2-orange.css, public/css/mambo-ui-0.0.2-purple.css, public/css/mambo-ui-0.0.2.css, public/index-dev.html, public/js/index-dev.js, public/js/index-prod.js, public/js/mambo-ui-0.0.2-stories.js, public/js/mambo-ui-0.0.2.js, src/ui/components/Toaster/story/toaster.js, src/ui/components/Tooltip/Tooltip-Orange.css, src/ui/components/Tooltip/Tooltip-Purple.css, src/ui/components/Tooltip/Tooltip.css, src/ui/components/Tooltip/Tooltip.js, src/ui/components/Tooltip/story/tooltip.js, src/ui/tools/Tags.js, src/ui/tools/Theme.js
Create Tooltip component and Story - Demo
Add default, orange and purple theme.
Update mamboUI js and theme css files for production
=> Add Tooltip Component

.idea/workspace.xml, public/css/mambo-ui-0.0.2-orange.css, public/css/mambo-ui-0.0.2-purple.css, public/css/mambo-ui-0.0.2.css, public/css/story.css, public/index-dev.html, public/js/index-dev.js, public/js/index-prod.js, public/js/mambo-ui-0.0.2-stories.js, public/js/mambo-ui-0.0.2.js, src/ui/components/Button/Button.js, src/ui/components/ButtonGroup/ButtonGroup.js, src/ui/components/ButtonGroup/story/buttonGroup.js, src/ui/components/Pagination/Pagination.css, src/ui/components/Pagination/Pagination.js, src/ui/components/Pagination/story/pagination.js, src/ui/tools/Tags.js, src/ui/tools/Theme.js
Create Pagination Component
Create Pagination Story
Add icons to previous and next buttons
=> Create pagination component

.idea/workspace.xml, src/ui/components/ButtonGroup/ButtonGroup.js, src/ui/components/ButtonGroup/story/buttonGroup.js
Added support for custom attributes and properties on the mambo-button-group container element
=> add attr and props configuration to mambo-button-group container

.idea/workspace.xml, src/ui/components/ListMenu/ListMenu-Orange.css, src/ui/components/ListMenu/ListMenu-Purple.css, src/ui/components/ListMenu/ListMenu.css, src/ui/components/ListMenu/ListMenu.js, src/ui/components/ListMenu/story/listMenu.js, src/ui/themes/m-default.css, src/ui/themes/m-orange.css, src/ui/themes/m-purple.css
Add `rotatable` prop to enable icon rotation on click
Rename `child` to `children` prop.  Allow nesting of child elements.
=> Change ListMenu

.idea/workspace.xml, public/css/storyboard.css, src/ui/components/MapBox/MapBox.css, src/ui/components/MapBox/MapBox.js, src/ui/components/MapBox/story/mapbox.js
Add custom loading message to mapbox
Change story mapbox container size
=> Add loadingMessage to mapbox

dist/0.0.3/mambo-ui-0.0.3-orange.css, dist/0.0.3/mambo-ui-0.0.3-purple.css, dist/0.0.3/mambo-ui-0.0.3.css, dist/0.0.3/mambo-ui-0.0.3.js, package-lock.json, package.json, public/css/mambo-ui-0.0.3-orange.css, public/css/mambo-ui-0.0.3-purple.css, public/css/mambo-ui-0.0.3.css, public/js/mambo-ui-0.0.3-stories.js, public/js/mambo-ui-0.0.3.js, setup/gulpfile.js
Se agrego el paquete gulp-ignore para corregir un error especifico de linux al crear el CSS bundle del tema default usando gulp.
Actualizacion de los JS builds y los CSS bundles en las carpeta public y dist
=> Corrección del CSS bundle del theme default

.idea/workspace.xml, dist/0.0.3/mambo-ui-0.0.3-orange.css, dist/0.0.3/mambo-ui-0.0.3-purple.css, dist/0.0.3/mambo-ui-0.0.3.css, public/css/mambo-ui-0.0.3-orange.css, public/css/mambo-ui-0.0.3-purple.css, public/css/mambo-ui-0.0.3.css, setup/gulpfile.js
Correccion de un error al generar los css bundles
=> fix css bundles

src/ui/components/Button/Button.js, src/ui/components/Input/Input-Orange.css, src/ui/components/Input/Input-Purple.css, src/ui/components/Input/Input.js, src/ui/components/Input/story/input.js
Agregue de los eventos touchstart y touchend a Button.
Agregue los eventos touchstart y touchend al leftButton del Input
Cambio font-size del texto required del Input
=> Agregado de eventos de touch a Button

.idea/workspace.xml, src/ui/components/Input/Input-Orange.css, src/ui/components/Input/Input-Purple.css, src/ui/components/Input/Input.css, src/ui/components/Input/Input.js, src/ui/components/Input/story/input.js, src/ui/tools/Tags.js, src/ui/tools/Theme.js
feat: add custom validations
feat: return errorMessage on dataValidationChange event
feat: add show (flag) to validate prop, to enable or disable displaying the error messages
=> [INPUT]: update validate function

.idea/workspace.xml, src/ui/components/Toaster/Toaster-Orange.css, src/ui/components/Toaster/Toaster-Purple.css, src/ui/components/Toaster/Toaster.css, src/ui/components/Toaster/Toaster.js, src/ui/components/Toaster/story/toaster.js, src/ui/themes/m-default.css, src/ui/themes/m-orange.css, src/ui/themes/m-purple.css, src/ui/tools/Theme.js
[Toaster]:
Add animations with customizable:
Position (x, y)
Duration
Distance
Add persistence option
Add initial state control (open/closed)
=> [Toaster]: Add animations, persistence and custom positioning

.idea/workspace.xml, documentation/documentation.md, public/css/mambo-ui-0.0.4-orange.css, public/css/mambo-ui-0.0.4-purple.css, public/css/mambo-ui-0.0.4.css, public/js/mambo-ui-0.0.4-stories.js, public/js/mambo-ui-0.0.4.js, src/ui/components/ListMenu/ListMenu-Orange.css, src/ui/components/ListMenu/ListMenu-Purple.css, src/ui/components/ListMenu/ListMenu.css, src/ui/components/ListMenu/ListMenu.js, src/ui/components/ListMenu/story/listMenu.js
Update mambo-list-menu component
add autoclose behaviour
change item background color
update documentation 
update css / js mambo files in public folder
=> [ListMenu]: update mambo-list-menu

.idea/workspace.xml, CHANGELOG.md, documentation/documentation.md, public/js/mambo-ui-0.0.4-stories.js, public/js/mambo-ui-0.0.4.js, src/ui/components/Toaster/Toaster.js, src/ui/components/Toaster/story/toaster.js
Add onClosed event when toaster close
Add autoHideDuration to set an internal timeout
Create new build and docs
Update changelog.md
=> [Update ] Toaster - add onClosed event and fix autoHideDuration

.idea/workspace.xml, public/css/mambo-ui-0.0.5-orange.css, public/css/mambo-ui-0.0.5-purple.css, public/css/mambo-ui-0.0.5.css, public/js/mambo-ui-0.0.5.js, src/ui/components/MapBox/MapBox.js
update: change setMarker method to public
=> update: change setMarker method to public

.idea/workspace.xml, src/ui/components/Button/Button-Orange.css, src/ui/components/Button/Button-Purple.css, src/ui/components/Button/Button.css
[mambo-button] 
Update .m-mambo-icon style to fix iOS centering issue
=> [MamboButton] update: change icon css style
